# Generated by Django 4.2.3 on 2023-08-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="addres",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="contact",
            old_name="emial",
            new_name="email",
        ),
    ]
